language: scala

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/local/lib

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

jdk:
  - openjdk8

dist: bionic
addons:
  apt:
    update: true
    packages:
      - libhdf5-dev
        
python: 3.6

install:
  - travis/netcdf_build.sh
  - python3.6 -m pip3 install jep

env:
  - LD_LIBRARY_PATH=$HOME/local/lib
