name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - uses: coursier/cache-action@v6
      - name: Update package lists
        run: sudo apt-get update
      - name: Install libhdf5-dev
        run: sudo apt-get install libhdf5-dev
      - name: Install libcurl-dev
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Set NetCDF install location
        run: echo "NETCDF_PATH=$HOME/netcdf" >> $GITHUB_ENV
      - name: Cache NetCDF installation
        id: cache-netcdf
        uses: actions/cache@v2
        with:
          path: ${{ env.NETCDF_PATH }}
          key: ${{ runner.os }}-netcdf-4.7.4
      - name: Install NetCDF
        if: steps.cache-netcdf.outputs.cache-hit != 'true'
        run: |
          cd $HOME
          curl -OL https://github.com/Unidata/netcdf-c/archive/v4.7.4.tar.gz
          tar -xf v4.7.4.tar.gz
          cd netcdf-c-4.7.4
          CPPFLAGS=-I/usr/include/hdf5/serial LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial ./configure --prefix=$NETCDF_PATH
          make install
      - name: Run tests
        run: sbt -v +test
        env:
          LD_LIBRARY_PATH: ${{ env.NETCDF_PATH }}/lib
